### PR TITLE
Throw errors when problems happen so we get non-zero exit codes

### LINKED ISSUE #239: When tool fails with "Unable to write output file" exit with non-zero exit code
Right now, even though it failed (in my particular case with `Unable to write output file: EACCES: permission denied, open 'scenarioConfig.json'`) it exits with code 0, which makes it hard to work with in CI/programmatic environments. Can it please be changed to have a non-zero exit code?

### PR DESCRIPTION
**Pull request by palfrey**
Please:
- [x] Do not include the compiled `.js`, `.js.map`, or `.d.ts` in your pull request as it makes it harder to merge your changes. 
- [x] Make your pull request atomic, fixing one issue at a time unless there are many relevant issues that cannot be decoupled.
- [x] Provide a test case & update the documentation in the `Readme.md`

Fixes #239

### CODE REVIEW

File: typescript-json-schema.ts [hunk 1]
```diff
@@ -1195,14 +1195,14 @@ export function exec(filePattern: string, fullTypeName: string, args = getDefaul
 
     const definition = generateSchema(program, fullTypeName, args, onlyIncludeFiles);
     if (definition === null) {
-        return;
+        throw new Error("No output definition. Probably caused by errors prior to this?");
```
Comment (domoritz) [inline typescript-json-schema.ts]: Can you give an example that triggers this line? I want to make sure that we want to raise an error here.

Comment (palfrey) [reply typescript-json-schema.ts]: Added a test case that does so
